language: python
python: 3.6
sudo: required

install:
  # Install Python packages
  - pip install -r requirements.txt
  # Install Source Code Pro fonts
  - sudo git clone --branch release --depth 1 'https://github.com/adobe-fonts/source-code-pro.git' /usr/share/fonts/opentype
  - fc-cache -f -v
  # Install tinytex (https://github.com/yihui/tinytex)
  # - wget -qO- "https://yihui.name/gh/tinytex/tools/install-unx.sh" | sh
  # Here install the tinytex binary package for travis, maintained by the tinytex author
  - curl -sSL https://raw.githubusercontent.com/yihui/tinytex/master/tools/download-travis-linux.sh | sh
  # Install extra tex packages
  - tlmgr install ctex ms xecjk ulem zhnumber fancyhdr titlesec tabulary varwidth
                  float wrapfig parskip capt-of needspace xcolor enumitem datetime2
                  tracklang fandol upquote

script:
  - make build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN}
  local_dir: build/dirhtml
  on:
    branch: master
